"use client"

import { motion } from "framer-motion"
import { ArrowRight } from "lucide-react"

interface UniverseCardProps {
  title: string
    subtitle: string
      tag: string
        image: string
          glow: string
            onClick?: () => void
            }

            export default function UniverseCard({
              title,
                subtitle,
                  tag,
                    image,
                      glow,
                        onClick,
                        }: UniverseCardProps) {
                          return (
                              <motion.div
                                    whileHover={{
                                            y: -10,
                                                    scale: 1.02,
                                                          }}
                                                                transition={{ duration: 0.4 }}
                                                                      onClick={onClick}
                                                                            className="group relative h-[520px] rounded-[32px] overflow-hidden cursor-pointer"
                                                                                >
                                                                                      {/* Background */}
                                                                                            <div
                                                                                                    className="absolute inset-0 bg-cover bg-center scale-100 group-hover:scale-110 transition-transform duration-700"
                                                                                                            style={{
                                                                                                                      backgroundImage: `url(${image})`,
                                                                                                                              }}
                                                                                                                                    />

                                                                                                                                          {/* Dark Overlay */}
                                                                                                                                                <div className="absolute inset-0 bg-black/45" />

                                                                                                                                                      {/* Glow */}
                                                                                                                                                            <div
                                                                                                                                                                    className={`absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-700 blur-3xl ${glow}`}
                                                                                                                                                                          />

                                                                                                                                                                                {/* Gradient */}
                                                                                                                                                                                      <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" />

                                                                                                                                                                                            {/* Content */}
                                                                                                                                                                                                  <div className="relative z-10 flex flex-col justify-between h-full p-8">
                                                                                                                                                                                                          {/* Tag */}
                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                            <span className="inline-flex px-4 py-2 rounded-full border border-white/10 bg-white/5 backdrop-blur-md text-white/70 text-xs tracking-[0.25em] uppercase">
                                                                                                                                                                                                                                        {tag}
                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                  {/* Bottom Content */}
                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                initial={{ opacity: 0.8 }}
                                                                                                                                                                                                                                                                                                            whileHover={{ opacity: 1 }}
                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                  <h2 className="text-4xl font-serif text-white mb-4 tracking-wide">
                                                                                                                                                                                                                                                                                                                                                {title}
                                                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                                                        <p className="text-white/70 text-lg leading-relaxed max-w-sm">
                                                                                                                                                                                                                                                                                                                                                                                      {subtitle}
                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                            whileHover={{ x: 6 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-8 flex items-center gap-3 text-gold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-sm tracking-[0.2em] uppercase">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Enter Laboratory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ArrowRight className="w-5 h-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Border Glow */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute inset-0 rounded-[32px] border border-white/10 group-hover:border-gold/40 transition-colors duration-500" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Reflection */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition duration-700 bg-gradient-to-br from-white/10 via-transparent to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }